import {
  IMAGE_ATTACHMENT_MIME_TYPES,
  attachmentCaptureRefusal,
  providerAcceptsImages,
  type AttachmentRefusal,
} from '@/conveyor/protocol/image-attachments'

/**
 * The composer's image rules: what a draft attachment is, what the picker offers, and the sentences the
 * composer shows when something is refused.
 *
 * Pure and renderer-only, and kept out of the component for the same reason `mentions.ts` is: appending
 * one image, wording a refusal and ordering the saves a send performs are decisions a test should be
 * able to make by calling a function, not by dropping a file on a textarea and inferring what happened.
 *
 * Every cap and every sentence about a cap is *imported*. `MAX_ATTACHMENT_BYTES`, the whitelist and the
 * per-message count are what main enforces on the wire, so the composer refusing at the same numbers is
 * the point of importing the rules rather than restating them — a second copy here would be a UI that
 * lets the user build a message the schema then refuses.
 */

/**
 * One image the composer is holding but has not sent.
 *
 * The bytes are held in memory for the life of the draft and are lost when the app closes, which is
 * deliberate and disclosed: nothing is written until the user sends, so an abandoned draft leaves no
 * folder behind and a pasted screenshot of something private never reaches the disk. What the send
 * stores is the same bytes, handed over once through `attachments.save`.
 *
 * `id` is generated by the renderer and is only ever a React key and a lookup for the object URL. It is
 * never the stored id — that one is main's, and it exists only after a save.
 */
export interface DraftAttachment {
  id: string
  /** The name the file arrived under, shown on the chip and carried into the reference for display. */
  name: string
  mimeType: string
  /** `bytes.byteLength`, kept beside them so a chip can show a size without measuring the array. */
  size: number
  /**
   * The bytes themselves.
   *
   * `ArrayBuffer` and not `ArrayBufferLike`, which is what an `ArrayBuffer` read from a file produces and
   * what the store's schema accepts. Naming the parameter is what keeps a shared backing buffer out of a
   * payload that crosses IPC: a typed array over a `SharedArrayBuffer` cannot be structured-cloned, and
   * this is where that is said rather than discovered at the boundary.
   */
  bytes: Uint8Array<ArrayBuffer>
}

/**
 * The filter the picker offers, built from the whitelist rather than written out.
 *
 * A comma-separated media-type list, which is what `accept` takes, so a browser that filters its dialog
 * and a rule that refuses at capture cannot come to offer different types: the whitelist is the one
 * list, and this is that list in the picker's spelling.
 */
export const ATTACHMENT_ACCEPT_ATTRIBUTE = IMAGE_ATTACHMENT_MIME_TYPES.join(',')

/** One image, described well enough to be shown on a chip: `2.4 MB`, `412 KB`, `1 byte`. */
export function attachmentSizeLabel(bytes: number): string {
  if (bytes < 1024) return `${bytes} ${bytes === 1 ? 'byte' : 'bytes'}`
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

/** Build a draft attachment from bytes already in hand, so the size can never disagree with them. */
export function draftAttachmentFrom(
  id: string,
  name: string,
  mimeType: string,
  bytes: Uint8Array<ArrayBuffer>
): DraftAttachment {
  return { id, name, mimeType, size: bytes.byteLength, bytes }
}

/**
 * What the composer says about a refusal, with the file named.
 *
 * The sentence is the rule's own — the same one main would refuse the write with — and the name is what
 * makes it about the file the user just chose rather than about attachments in general. A refusal that
 * said only "this file is too large" would leave a user who dropped four files at once unable to tell
 * which one it was.
 */
export function attachmentRefusalNotice(name: string, refusal: AttachmentRefusal): string {
  return `${name}: ${refusal.message}`
}

/**
 * What the composer says when the current provider is not marked image-capable.
 *
 * The renderer's sentence and not a protocol one, because no rule was broken: the provider record simply
 * carries no permission, and the useful thing to say is where that is turned on. The provider is named
 * because the setting is per provider, and the user has more than one.
 */
export function imageCapabilityNotice(providerName: string): string {
  return `${providerName} is not set up to take images. Switch on image support in Settings, under Providers.`
}

/** Why an attempt added nothing, or what it added. */
export interface AttachmentRefusalResult {
  /** The draft, untouched when something was refused — what a user sees as a refusal is nothing changing. */
  draft: DraftAttachment[]
  /** The sentence to show, or null when the image was taken. */
  notice: string | null
}

/**
 * Take one image into the draft, or say why it was not taken.
 *
 * The gate is deliberately *not* asked here. Refusing for a provider that is not marked image-capable is
 * the caller's step, because the sentence names the provider and this file has no idea which one is on
 * screen — and a function that answered "refused" with `notice: null` would be one no caller could tell
 * apart from "taken".
 *
 * What is asked here is the shared rules, through `attachmentCaptureRefusal` and against the count the
 * draft already holds, so the cap is enforced against the message this image would join.
 *
 * Appending is the whole of the ordering policy: the array's order *is* attach order, which is what the
 * chips show, what the saves are dispatched in and what the turn's references are written in.
 */
export function addDraftAttachment(
  draft: readonly DraftAttachment[],
  candidate: { name: string; mimeType: string; bytes: Uint8Array<ArrayBuffer> }
): AttachmentRefusalResult {
  const refusal = attachmentCaptureRefusal({
    mimeType: candidate.mimeType,
    bytes: candidate.bytes.byteLength,
    attached: draft.length,
  })
  if (refusal) return { draft: [...draft], notice: attachmentRefusalNotice(candidate.name, refusal) }

  return {
    draft: [...draft, draftAttachmentFrom(nextDraftId(), candidate.name, candidate.mimeType, candidate.bytes)],
    notice: null,
  }
}

/** Drop one image, keeping the order of the rest: the order is the user's and is what a send reads. */
export function removeDraftAttachment(draft: readonly DraftAttachment[], id: string): DraftAttachment[] {
  return draft.filter((attachment) => attachment.id !== id)
}

/** One image, as the send hands it to `attachments.save`. */
export interface AttachmentSaveRequest {
  sessionId: string
  name: string
  mimeType: string
  bytes: Uint8Array<ArrayBuffer>
}

/**
 * The saves a send performs, one per image, in attach order.
 *
 * Stated as a function rather than left inline because the order is a promise the rest of the feature
 * rests on: the references come back one per request, and the renderer awaits them in sequence, so this
 * array's order *is* the order of `imageRefs` on the turn, which is the order the model reads the parts
 * in. A save dispatched from a `Set`, or built from a lookup by name, would still store every image and
 * would still send them in an order the user did not choose — the silent failure this exists to prevent.
 */
export function attachmentSaveRequests(sessionId: string, draft: readonly DraftAttachment[]): AttachmentSaveRequest[] {
  return draft.map((attachment) => ({
    sessionId,
    name: attachment.name,
    mimeType: attachment.mimeType,
    bytes: attachment.bytes,
  }))
}

/**
 * The files a paste, a drop or a picker is carrying, in the order it lists them.
 *
 * Takes the structural shape rather than `DataTransfer`, and that is not only for the tests: a clipboard
 * payload, a drag payload and an input's own list all expose `files`, and a helper written against one of
 * the three would have had to be copied for the other two. An empty or absent list is an empty return
 * rather than an error, which is what a paste carrying only prose is.
 */
export function filesIn(source: { files?: ArrayLike<File> | null } | null | undefined): File[] {
  const files = source?.files
  return files ? Array.from(files) : []
}

/**
 * Whether the provider on screen may take images, read through the pure gate.
 *
 * One call rather than the comparison inline, so the composer, the picker button and every capture path
 * are answering the same question the same way.
 */
export function composerAcceptsImages(provider: unknown): boolean {
  return providerAcceptsImages(provider)
}

/**
 * A draft's own id, for the React key and the object URL's bookkeeping.
 *
 * A module-scope sequence rather than a counter in the pane, and that is the point: the draft survives a
 * keyed remount while the pane that built it does not, so a counter living in the pane would restart at
 * one beside attachments that are still there — and two chips would share a key.
 */
let draftSequence = 0

function nextDraftId(): string {
  draftSequence += 1
  return `draft-image-${draftSequence}`
}
