/**
 * The docx conversion wrapper, through the real mammoth.
 *
 * The claim being made is that this app can turn a Word container into HTML, and the only evidence for
 * it is mammoth itself reading a real one. So the fixture is a genuine `.docx` — four parts, built by
 * `tests/probes/make-docx-fixture.mjs` and carried here as base64 — and the assertion is made on the
 * paragraph text mammoth's own reader produces. A stub would prove the plumbing and nothing about the
 * format, which is the half of this that can actually be wrong.
 *
 * The refusal is the other half: bytes that are not a container at all must come back as a sentence
 * rather than as mammoth's own complaint about a central directory. That wording is this app's, which
 * is why it is asserted here rather than left to the browser to render.
 */
import { strict as assert } from 'node:assert'
import { docxToHtml } from '../../app/components/workbench/docx'

const results: string[] = []

async function step(label: string, fn: () => void | Promise<void>): Promise<void> {
  process.stdout.write(`... ${label}\n`)
  await fn()
}

/**
 * A minimal Word document, base64.
 *
 * Generated by `node tests/probes/make-docx-fixture.mjs`, which is the same container written out part
 * by part: `[Content_Types].xml`, the package relationships, an empty relationship list for the
 * document part, and a `word/document.xml` holding the two paragraphs asserted below. Stored rather
 * than deflated, so the constant is reproducible from the probe and the bytes in it are the bytes the
 * parts were.
 */
const DOCX_FIXTURE_BASE64 =
  'UEsDBAoAAAAAAE5eQl3JTxqwrgEAAK4BAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbDw/eG1sIHZlcnNpb249IjEuMCIgZW5j' +
  'b2Rpbmc9IlVURi04IiBzdGFuZGFsb25lPSJ5ZXMiPz4KPFR5cGVzIHhtbG5zPSJodHRwOi8vc2NoZW1hcy5vcGVueG1sZm9y' +
  'bWF0cy5vcmcvcGFja2FnZS8yMDA2L2NvbnRlbnQtdHlwZXMiPjxEZWZhdWx0IEV4dGVuc2lvbj0icmVscyIgQ29udGVudFR5' +
  'cGU9ImFwcGxpY2F0aW9uL3ZuZC5vcGVueG1sZm9ybWF0cy1wYWNrYWdlLnJlbGF0aW9uc2hpcHMreG1sIi8+PERlZmF1bHQg' +
  'RXh0ZW5zaW9uPSJ4bWwiIENvbnRlbnRUeXBlPSJhcHBsaWNhdGlvbi94bWwiLz48T3ZlcnJpZGUgUGFydE5hbWU9Ii93b3Jk' +
  'L2RvY3VtZW50LnhtbCIgQ29udGVudFR5cGU9ImFwcGxpY2F0aW9uL3ZuZC5vcGVueG1sZm9ybWF0cy1vZmZpY2Vkb2N1bWVu' +
  'dC53b3JkcHJvY2Vzc2luZ21sLmRvY3VtZW50Lm1haW4reG1sIi8+PC9UeXBlcz5QSwMECgAAAAAATl5CXQAAAAAAAAAAAAAA' +
  'AAYAAABfcmVscy9QSwMECgAAAAAATl5CXbmBRHEqAQAAKgEAAAsAAABfcmVscy8ucmVsczw/eG1sIHZlcnNpb249IjEuMCIg' +
  'ZW5jb2Rpbmc9IlVURi04IiBzdGFuZGFsb25lPSJ5ZXMiPz4KPFJlbGF0aW9uc2hpcHMgeG1sbnM9Imh0dHA6Ly9zY2hlbWFz' +
  'Lm9wZW54bWxmb3JtYXRzLm9yZy9wYWNrYWdlLzIwMDYvcmVsYXRpb25zaGlwcyI+PFJlbGF0aW9uc2hpcCBJZD0icklkMSIg' +
  'VHlwZT0iaHR0cDovL3NjaGVtYXMub3BlbnhtbGZvcm1hdHMub3JnL29mZmljZURvY3VtZW50LzIwMDYvcmVsYXRpb25zaGlw' +
  'cy9vZmZpY2VEb2N1bWVudCIgVGFyZ2V0PSJ3b3JkL2RvY3VtZW50LnhtbCIvPjwvUmVsYXRpb25zaGlwcz5QSwMECgAAAAAA' +
  'Tl5CXQAAAAAAAAAAAAAAAAUAAAB3b3JkL1BLAwQKAAAAAABOXkJdAAAAAAAAAAAAAAAACwAAAHdvcmQvX3JlbHMvUEsDBAoA' +
  'AAAAAE5eQl0oRiWwnAAAAJwAAAAcAAAAd29yZC9fcmVscy9kb2N1bWVudC54bWwucmVsczw/eG1sIHZlcnNpb249IjEuMCIg' +
  'ZW5jb2Rpbmc9IlVURi04IiBzdGFuZGFsb25lPSJ5ZXMiPz4KPFJlbGF0aW9uc2hpcHMgeG1sbnM9Imh0dHA6Ly9zY2hlbWFz' +
  'Lm9wZW54bWxmb3JtYXRzLm9yZy9wYWNrYWdlLzIwMDYvcmVsYXRpb25zaGlwcyI+PC9SZWxhdGlvbnNoaXBzPlBLAwQKAAAA' +
  'AABOXkJdAO80xhQBAAAUAQAAEQAAAHdvcmQvZG9jdW1lbnQueG1sPD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRG' +
  'LTgiIHN0YW5kYWxvbmU9InllcyI/Pgo8dzpkb2N1bWVudCB4bWxuczp3PSJodHRwOi8vc2NoZW1hcy5vcGVueG1sZm9ybWF0' +
  'cy5vcmcvd29yZHByb2Nlc3NpbmdtbC8yMDA2L21haW4iPjx3OmJvZHk+PHc6cD48dzpyPjx3OnQ+SGVsbG8gZnJvbSB0aGUg' +
  'ZG9jdW1lbnQuPC93OnQ+PC93OnI+PC93OnA+PHc6cD48dzpyPjx3OnQ+U2Vjb25kIHBhcmFncmFwaC48L3c6dD48L3c6cj48' +
  'L3c6cD48L3c6Ym9keT48L3c6ZG9jdW1lbnQ+UEsBAhQACgAAAAAATl5CXclPGrCuAQAArgEAABMAAAAAAAAAAAAAAAAAAAAA' +
  'AFtDb250ZW50X1R5cGVzXS54bWxQSwECFAAKAAAAAABOXkJdAAAAAAAAAAAAAAAABgAAAAAAAAAAABAAAADfAQAAX3JlbHMv' +
  'UEsBAhQACgAAAAAATl5CXbmBRHEqAQAAKgEAAAsAAAAAAAAAAAAAAAAAAwIAAF9yZWxzLy5yZWxzUEsBAhQACgAAAAAATl5C' +
  'XQAAAAAAAAAAAAAAAAUAAAAAAAAAAAAQAAAAVgMAAHdvcmQvUEsBAhQACgAAAAAATl5CXQAAAAAAAAAAAAAAAAsAAAAAAAAA' +
  'AAAQAAAAeQMAAHdvcmQvX3JlbHMvUEsBAhQACgAAAAAATl5CXShGJbCcAAAAnAAAABwAAAAAAAAAAAAAAAAAogMAAHdvcmQv' +
  'X3JlbHMvZG9jdW1lbnQueG1sLnJlbHNQSwECFAAKAAAAAABOXkJdAO80xhQBAAAUAQAAEQAAAAAAAAAAAAAAAAB4BAAAd29y' +
  'ZC9kb2N1bWVudC54bWxQSwUGAAAAAAcABwCjAQAAuwUAAAAA'

/** The fixture as the bytes the wrapper is handed, which is how the bridge's base64 arrives. */
function fixtureBytes(): Uint8Array {
  return new Uint8Array(Buffer.from(DOCX_FIXTURE_BASE64, 'base64'))
}

const ZIP_SIGNATURE = [0x50, 0x4b, 0x03, 0x04]

function theFixtureIsAContainer() {
  const bytes = fixtureBytes()
  assert.deepEqual(Array.from(bytes.slice(0, 4)), ZIP_SIGNATURE, 'the fixture starts with a zip header')
  // No assertion below is worth anything if this constant were empty or mis-encoded, so it is pinned
  // here rather than trusted.
  assert.ok(bytes.length > 1000, 'and it carries a whole container')
  results.push('the fixture decodes to a real zip container')
}

async function aWordDocumentBecomesItsParagraphs() {
  const conversion = await docxToHtml(fixtureBytes())

  assert.equal(conversion.ok, true, `a real docx converts: ${conversion.ok ? '' : conversion.message}`)
  if (!conversion.ok) return
  assert.ok(conversion.html.includes('Hello from the document.'), 'the first paragraph is in the html')
  assert.ok(conversion.html.includes('Second paragraph.'), 'and the second one')
  assert.ok(conversion.html.includes('<p>'), 'as elements rather than as bare text')
  results.push('a docx converts to html carrying its own paragraph text')
}

async function bytesThatAreNotAContainerAreRefusedInWords() {
  const notAContainer = new TextEncoder().encode('this is plainly not a Word document')

  const conversion = await docxToHtml(notAContainer)

  assert.equal(conversion.ok, false, 'plain text is not a docx')
  if (conversion.ok) return
  assert.ok(conversion.message.includes('Word'), `the refusal names the format: ${conversion.message}`)
  assert.ok(conversion.message.trim().length > 10, 'and reads as a sentence rather than as a code')
  results.push('bytes that are not a container are refused in this app’s own wording')
}

async function anEmptyBufferIsRefusedTheSameWay() {
  const conversion = await docxToHtml(new Uint8Array(0))

  assert.equal(conversion.ok, false, 'an empty buffer is not a docx either')
  results.push('an empty buffer is refused rather than converted to empty html')
}

// ---------------------------------------------------------------- harness

async function main() {
  await step('fixture: container', theFixtureIsAContainer)
  await step('convert: paragraphs', aWordDocumentBecomesItsParagraphs)
  await step('refuse: not a container', bytesThatAreNotAContainerAreRefusedInWords)
  await step('refuse: empty', anEmptyBufferIsRefusedTheSameWay)

  console.log(`docx convert: ${results.length} passed`)
  for (const r of results) console.log(`  pass: ${r}`)
}

void main().catch((err) => {
  console.error('DOCX CONVERT TEST FAILED:', err)
  process.exit(1)
})
